#+TITLE: Goals 2013 Descriptives
#+OPTIONS: toc:nil
#+AUTHOR: Ethan Brown
#+LaTex_HEADER: \usepackage[cm]{fullpage}
#+LaTex_HEADER: \pagestyle{empty}
#+LaTex_HEADER: \thispagestyle{empty}
#+LaTex_HEADER: \DeclareUnicodeCharacter{00A0}{~}

* Setup
#+BEGIN_SRC R :ravel setup
  source("/home/fortis/goals-2013/functions.R")
  
  gp.raw <- read.csv("/home/fortis/goals-2013/data-in/GOALS-DEIDENTIFIED-2013-12-20.csv")
  
  ## Exclude non-consenting
  summary(factor(gp.raw$consent)) ## no missing values; 38 nonconsenting, 1165 consenting
  gp <- gp.raw[ gp.raw$consent == 1, ] ## 2 = non-consenting
  
  ## Replace response numeric codes with factors for reasonable summarizing
  responsecols <- grep("^q..$", names(gp), value = T)
  gp[,responsecols] <- lapply(gp[,responsecols], factor)
  
  rwcols <- paste0(responsecols, ".rw")
  gp.rw <- gp[, rwcols]
#+END_SRC

#+BEGIN_SRC R :revel recode
  ## Add response options
  
  ## sampling items
  gp$q06 <- factor(gp$q06, labels = c("Valid", "Invalid"))
  gp$q09 <- factor(gp$q09, labels = c("Same", "Small n is wider", "Large n is wider"))
  gp$q13 <- factor(gp$q13, labels = c("Small n is wider", "Large n is wider", "Same"))
  gp$q23 <- factor(gp$q23, labels = c("Smaller than original", "Same as original", "Larger than original"))
  
  ## center items
  gp$q10 <- factor(gp$q10, labels = c("Standard medication", "New medication", "Neither"))
  gp$q11 <- factor(gp$q11, labels = c("Smaller difference", "Larger difference", "Same evidence"))
  
  ## Variability items
  
  gp$q08 <- factor(gp$q08, labels = c("Uniform", "Unimodal", "Neither"))
  gp$q12 <- factor(gp$q12, labels = c("Smaller variability", "Larger variability", "Same evidence"))
#+END_SRC

#+BEGIN_SRC R
  save(list = c("gp", "gp.rw"), file = "/home/fortis/goals-2013/data-in/g2013-clean.Rda")
#+END_SRC
* Missing values
#+BEGIN_SRC R
table(gp$missing)
#+END_SRC


* Items

** All Items
| *Items* | *Measured Learning Goal*                                                                                                                     |
|---------+----------------------------------------------------------------------------------------------------------------------------------------------|
|       1 | Able to reason about the purpose of random assignment                                                                                        |
|       2 | Able to reason about the factors that allow a sample of data to be representative of the population.                                         |
|       3 | Able to reason about how correlation does not imply causation.                                                                               |
|       4 | Able to reason about the effect of  moving an influential point to a new location on the correlation coefficient                             |
|       5 | Able to reason that no statistical significance does not guarantee that there is no effect.                                                  |
|       6 | Able to reason about the relationship between sample size and statistical significance                                                       |
|       7 | Able to reason about factors that affect the mean and median                                                                                 |
|       8 | Able to reason that given two distributions that have the same range, the one with less mass in the center has the larger standard deviation |
|       9 | Able to reason about differences between empirical sampling distributions for large and small sample sizes.                                  |
|      10 | Able to reason about how to judge differences when visually comparing two samples of data.                                                   |
|      11 | Able to reason about how differences in center affect strength of evidence against the null hypothesis of no difference                      |
|      12 | Able to reason about how differences in variability affect strength of evidence against the null hypothesis of no difference                 |
|      13 | Able to reason about how the width of a confidence interval is related to sample size.                                                       |
|      14 | Able to reason about how the width of a confidence interval is related to level of confidence.                                               |
|      15 | Able to reason about a misinterpretation of a confidence level (the range of observed values for individual observational units or cases)    |
|      16 | Able to reason about a misinterpretation of a confidence level (using it to make a prediction for a single case)                             |
|      17 | Able to reason about what the null model represents in a research study                                                                      |
|      18 | Able to reason about what model should be used for the null hypothesis when comparing two groups                                             |
|      19 | Able to reason about how to find a p-value based on simulation results.                                                                      |
|      20 | Able to reason about a conclusion based on a statistically significant p-value in the context of a research study that compares two groups   |
|      21 | Able to reason about an incorrect interpretation of a p-value (probability of a treatment being more effective).                             |
|      22 | Able to reason about the correct interpretation of a p-value.                                                                                |
|      23 | Able to reason about how increasing the sample size affects the p-value, all else being equal.                                               |
#+TBLFM: $1=@#-1

#+BEGIN_SRC R :ravel corrgram,fig=TRUE
  corrgram(gp.rw, cex.labels = 1.5, lower.panel = panel.shade, upper.panel = panel.pie)
#+END_SRC

Bivariate correlations seem generally quite low.  The mean/median item (q07) has among the largest number of substantially correlated items.  q09, the candies item, and q13, the CI/Sample size item, both have a lot of healthy intercorrelations.

The Alice testlet seems to pop out quite separately from the other items... we may be getting a very different group of students who do well on the Alice items than the others (but this conclusion should be taken with caution as it's based only on bivariate correlations).  It would be interesting to do some principle components on this.

#+BEGIN_SRC R :ravel percentCorrect,fig=TRUE,width=9, height=6
  pc <- colMeans(gp.rw, na.rm = T)
  round(pc, 2)
  
  names(pc) <- 1:23
  barplot(pc, las = 2)
  
#+END_SRC



*** TODO replace this table with glosses/descriptions of the items for quick reference


** Sample size
| *Items* | *Gloss*                                           |
|---------+-----------------------------sweave change figure size----------------------|
|       6 | Herbicide: sample size may be why not significant |
|       9 | Candies problem (visual)                          |
|      13 | CI/Sample size                                    |
|      23 | Increase in sample size -> p-value                |

#+BEGIN_SRC R :ravel sample.size
  samps <- c("q06", "q09", "q13", "q23")
  samps.rw <- paste0(samps, ".rw")
  
  summary(gp[,sort(c(samps, samps.rw))])
  round(cor(gp[,samps.rw], use = "complete.obs"), 2)
#+END_SRC

As noted above in ``All Items'', both 9 and 13 are items that seem to have a lot in common with several other items, although I haven't seen whether those items are all visual items (both 9 and 13 are visual).

q06, the herbicide item, was one of the easier items, with 72\% correct.  The item presents subjects with the possibility that too small sample size, even in the presence of an effect, may account for the finding.

Formally, this is rather similar to q23, also an entirely verbal item, which asks students to see what would happen what would happen to the sample size if they got the same effect with a larger sample.  But, that was a much harder item (45 \% correct), and the correlation between the two appears to be rather low. The more popular distractor was to say that the p-value would be the same in the larger sample size, which is what we would expect when people do not incorporate the effect of sample size on sampling variability.  But there may be a good deal of other misunderstandings built into these responses, because that would presuppose that people showed good understanding of the p-value as well.

People did better on the candies problem... I believe the previous performance was in the 20s or 30s?  Here, 50% got it correct.  It's a few less steps now, we directly ask to evaluate the variability of the sampling distribution, rather than asking them to reason about the likelihood of a deviation from expectation. One way to solve this is to follow through the /logical consequences/ of the variability, but that adds steps onto the task.  The dominant misconception is, as before, that the larger and smaller have the same variability, but something about seeing this representation may cue them to think in a different manner about the issue.

Interestingly, the dominant misconception on the confidence interval one (which was also near 50\%) was that the larger sample size would have a larger confidence interval.  We have no idea how students are thinking about this, but it may be due to the complicated nature of confidence intervals more than a conception about the empirical distribution of sample statistics. It'd be interesting to crosstab these two.


*** TODO Compare p-value item to other p-value items... what happens to those who get the other two /right/?

*** TODO In general, I could do an analysis of performance on sample size items among the highest-performing students that appear to show good reasoning skills about everything besides for sample size.

Or look at different slices of students at different total (or total-minus-sample-size) levels


*** TODO crosstab/mosaic plot of q09 vs q13


** Focus on center
| *Items* | *Gloss*                   |
|---------+---------------------------|
|      10 | Headache problem          |
|      11 | Weight training 1: center |

I didn't include q07, the mean/median item, because it's not really about inference; instead, it's about what /affects/ the mean and median.
#+BEGIN_SRC R :ravel central
  cents <- c("q10", "q11")
  cents.rw <- paste0(cents, ".rw")
  
  summary(gp[,sort(c(cents, cents.rw))])
  round(cor(gp[,cents.rw], use = "complete.obs"), 2)
#+END_SRC


** Variability
| *Items* | *Gloss*                        |
|---------+--------------------------------|
|       8 | Standard deviation dotplots    |
|      12 | Weight training 2: variability |


#+BEGIN_SRC R :ravel variability 
  vars <- c("q08", "q12")
  vars.rw <- paste0(vars, ".rw")
  
  summary(gp[,sort(c(vars, vars.rw))])
  round(cor(gp[,vars.rw], use = "complete.obs"), 2)
#+END_SRC
